### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by Drigax** [DanielBorgesOliveira/onedrive_tray#1]
Hi,

I'm really excited to try this tool. Do you have a build command or makefile that you can add to the repo? I'd like to give this a shot, but I'm not sure how to link against QT

**Comment by DanielBorgesOliveira** [comment]
Hi @Drigax 

To compile the program you should call qmake tool. It will create the Makefile.

The steps bellow should be suffice to compile the program:

$ git clone https://github.com/DanielBorgesOliveira/onedrive_tray.git
$ cd onedrive_tray
$ mkdir build
$ cd build
$ qmake ../systray.pro
$ make

This will create systray binary.

I compiled it with QT 5.12.6 and 5.13.0 without problem. I am not sure if other versions of QT will work. 

Hope this helps you.

**Comment by Drigax** [comment]
Thanks! I'll give this a shot later today

**Comment by raoulteeuwen** [comment]
Fyi: on Kubuntu i had to add "sudo apt install qt5-default", since without this, i would be thrown a "qmake: could not find a Qt installation of ''" at step "qmake..."

**Comment by DanielBorgesOliveira** [comment]
That is right @raoulteeuwen.

It is possible to use the package provided by QT company too. It is available at https://www.qt.io/download-open-source.

**Comment by thomaswwp** [comment]
Thanks for this. Just built it and got it working on Debian Buster. A couple of comments/questions:

1) I think editing the line 47 or windows.cpp is now no longer needed?
2) The binary `systray` that appears in build can be renamed onedrive-systray and put in my `~bin` folder and run every login by putting it in `.xinitrc` (not sure that is the correct way to do it, I am pretty new to Linux, but that seemed sensible to me!)
3) If running this, it replaces onedrive as a service so `systemctl --user disable onedrive`

**Comment by DanielBorgesOliveira** [comment]
Hi @thomaswwp ,

1 - You are right. There is no need anymore to edit the windows.cpp file. I just updated the README.md with the new instructions.
2 - Correct. I put instructions about this in README.md.
3 - Yes. That is right. You should disable the onedrive service.
4 - Nice. I use bspwm with xfce4-panel. I put a call to the script autostart in "~/.config/bspwm/bspwmrc" and put the call to onedrive-tray in ".~/config/bspwm/autostart".

The call in autostart file in my case is: 

/usr/local/bin/onedrive_tray --onedrive-path "/usr/local/bin/onedrive"  --onedrive-args "--monitor --local-first --skip-symlinks --confdir /home/daniel/.config/onedrive" &

**Comment by TechSupport26** [comment]
I just wanted to add. For Debian I installed qtbase5-dev and then I was able to run qmake ../systray.pro however I got stuck at this step
onedrive_tray --onedrive-path [path to onedrive client] --onedrive-args [onedrive client arguments].
