### ISSUE TITLE
Duplicate icon on system tray

### ISSUE THREAD

**Issue by luoiliembac** [DanielBorgesOliveira/onedrive_tray#11]
Thank you very much for your great work!

The icon works almost perfect, except for the situation that there are more icons added to the system tray when restarting the system. That means every time Linux restart, there is one more icon appears, and then another one, and so on.
I have to click Quit manually for each icon.
I am using Manjaro KDE.

Hope to solve this, and then everything is perfect!

**Comment by DanielBorgesOliveira** [comment]
Hi @luoiliembac,

I have never seen this before.
Maybe this is specific about your distribution.
Can you make a video showing what is happening and send me?
Maybe I can see more clearly what can we do to solve the problem with a video.

**Comment by DanielBorgesOliveira** [comment]
Looks like the user solved the problem.
