### ISSUE TITLE
Provide different icon for dark themes

### ISSUE THREAD

**Issue by willydee** [DanielBorgesOliveira/onedrive_tray#12]
### Description

In a dark theme (my DE: GNOME 40, Theme Arc-Flatabulous-Dark, Iconset Papirus-Dark) the tray icon is lacking contrast and is almost indistinguishable from its background. Please consider adding support for detecting the desktop theme, and an additional white-colored icon.

![image](https://user-images.githubusercontent.com/7428576/113907703-f8a01100-97d5-11eb-86b8-6208b90703da.png)

**Comment by DanielBorgesOliveira** [comment]
Hi @willydee ,

I implemented support to some different colors.
Look if it can help you.

Thanks for your question.

**Comment by Niwton** [comment]
It would be a great white color to match the dark plasma breeze theme.[](url)
![Screenshot_20210515_133302](https://user-images.githubusercontent.com/24793957/118371340-8f54b000-b582-11eb-9eaf-df1890cabf88.png)
