### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by bforest76** [DanielBorgesOliveira/onedrive_tray#22]
Hello Daniel,
Thanks a lot for your program, it's very useful !
I am writing a new version with some more features
- translation management (and as I'm french I created a onedrive_tray_fr.qm file)
- icon color choice with QColorDialog and a dynamic color icon management
- application settings : saved and loaded  (icon color for example)
- a different icon when syncing (cloud with rain)
- show the remaining space on OneDrive
- show the status
- add an about box
- fix an open folder issue 
- and many other...
I'm still working on it because I still have many ideas. And as I'm a early learner of Qt and C++, I develop not quickly.

![menu_fr](https://user-images.githubusercontent.com/103065588/161844563-7eb15eae-67b0-4164-8ce6-29e31239ddd9.png)
![menu_en](https://user-images.githubusercontent.com/103065588/161844565-9125450c-0422-460c-bebc-2341511144b8.png)
![about_en](https://user-images.githubusercontent.com/103065588/161844567-c794fe87-825d-4024-9909-61262fe54170.png)

My problem : I'm a new user of github and I don't know how to share my program and how to obtain your agreement for this new version. Must I create a fork ? Or something different ?

Best regards,
Bruno

**Comment by DanielBorgesOliveira** [comment]
Hi Bruno,

Very nice work you did.
Congratulations!!

The best way you can contribute to the code is to make a pull request.
To do this follow the steps:
1. Fork the repository in your GitHub account;
2. Clone the forked repository in your machine;
3. Make the developments as you wish in the code;
4. Commit and push the code to your forked repository. This will make your public repository equal to your local code.
5. In the online GitHub account, create a pull request.

This video here explains the process in a simple way: [https://www.youtube.com/watch?v=rgbCcBNZcdQ](https://www.youtube.com/watch?v=rgbCcBNZcdQ).

If you have problems, either way, you can send me the code and I will try to put it online.
