### ISSUE TITLE
Clicking on open folder crashes the systemd service

### ISSUE THREAD

**Issue by sbeve72** [DanielBorgesOliveira/onedrive_tray#25]
Basically the title, I installed it using the command `sudo make install` and enabled the systemctl service and started it. After that my folder appeared in the systray. Everything's fine so far. But when I click on "Open Folder" after right clicking on the icon, the service crashes and restarts after a few seconds.

**Comment by bforest76** [comment]
@sbeve72  You can try the new version published last week-end. It includes some new features and I think that what you expect is in.

**Comment by DanielBorgesOliveira** [comment]
As @bforest76 said, try o update the code. Maybe this can solve the problem. If not, try to install another file manager. I had some problems like you said when I was using an older version of Thunar in a Debian 8.

**Comment by sbeve72** [comment]
> @sbeve72 You can try the new version published last week-end. It includes some new features and I think that what you expect is in.

That fixed it
