### ISSUE TITLE
[Enhancement] Add svg support to prevent blurry icons

### ISSUE THREAD

**Issue by Laurens256** [DanielBorgesOliveira/onedrive_tray#30]
Especially in larger toolbars/menus, icons can become quite blurry. Adding proper support for scaling .svg would fix this
![image](https://user-images.githubusercontent.com/85798751/180603029-2045daf4-d8b6-49a6-9b9e-2ada215c4b0d.png)

**Comment by DanielBorgesOliveira** [comment]
Hi Lauren,

Do you have some ideas for how can I do this?
I will try to take a look at this, but maybe you can help me.

Thank you very much.

**Comment by Laurens256** [comment]
To be honest, I don't have much experience with QT/C++ in general. I will look into it though
