### ISSUE TITLE
Error running 'lupdate'.

### ISSUE THREAD

**Issue by drivador** [DanielBorgesOliveira/onedrive_tray#36]
In the paragraph where you explain how to create a translation, I suggest an auxiliary addendum because in case we don't have all the basis for programming in Qt, the 'lupdate' command ends up in error. So I would quote:
If "lupdate" responds with the error “could not exec /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate: No such file or directory” execute:
$ sudo apt-get install qttools5-dev-tools

**Comment by Polda18** [comment]
Arch Linux user here. Apparently, Qt is a paid software. Not good if you want to add translations and don't have spare money to buy the software.

**Comment by DanielBorgesOliveira** [comment]
> In the paragraph where you explain how to create a translation, I suggest an auxiliary addendum because in case we don't have all the basis for programming in Qt, the 'lupdate' command ends up in error. So I would quote: If "lupdate" responds with the error “could not exec /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate: No such file or directory” execute: $ sudo apt-get install qttools5-dev-tools

Done! Thank you!

**Comment by DanielBorgesOliveira** [comment]
Solved.
