### ISSUE TITLE
how to remove it? 

### ISSUE THREAD

**Issue by alansenairj** [DanielBorgesOliveira/onedrive_tray#38]
it is not working well. how can I remove it? 

root@z390 /usr/local/bin # systemctl disable --user onedrive_tray.service   [0]
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)

**Comment by alansenairj** [comment]
Sep 25 14:05:57 z390 onedrive_tray[4567]: This application failed to start because no Qt platform plugin could>
                                          
                                          Available platform plugins are: eglfs, linuxfb, minimal, minimalegl,>
Sep 25 14:05:58 z390 systemd-coredump[4591]: [🡕] Process 4567 (onedrive_tray) of user 1000 dumped core.
                                             
                                             Found module linux-vdso.so.1 with build-id: 4eb75a990aa2bed3769eb>
                                             Found module libuuid.so.1 with build-id: 52d4ea2a005c5cbce6e92f00>
                                             Found module libxcb-util.so.1 with build-id: 9accdd80596ded214819>
                                             Found module libdbus-1.so.3 with build-id: a8d9a4e12c86b445bf8e57>
                                             Found module libxml2.so.2 with build-id: ec29498ecfb6c436ada6de0a>
                                             Found module libxkbcommon.so.0 with build-id: 534d0218e01a780844e>
                                             Found module libxkbcommon-x11.so.0 with build-id: 994928a128d5781>
                                             Found module libICE.so.6 with build-id: 322afa55205247e8243671021>
                                             Found module libSM.so.6 with build-id: 66be9db349cf0e0925db17296f>
                                             Found module libxcb-xinput.so.0 with build-id: c896104301f4b9aad0>
                                             Found module libxcb-xkb.so.1 with build-id: 90e440e5d8244a9d0a543>
                                             Found module libxcb-xinerama.so.0 with build-id: d6e17a6236c3d523>
                                             Found module libxcb-xfixes.so.0 with build-id: 445ec83da19adc83db>
                                             Found module libxcb-sync.so.1 with build-id: 921c84206950693d4737>
                                             Found module libxcb-shape.so.0 with build-id: cc87005fedca0f9aa98>
                                             Found module libxcb-render.so.0 with build-id: 36edcc5980076552c6>
                                             Found module libxcb-render-util.so.0 with build-id: 50ee35ba6a075>
                                             Found module libxcb-randr.so.0 with build-id: 53b21b081d50a0732aa>
                                             Found module libxcb-keysyms.so.1 with build-id: 7c10ab2b53bd04ced>
                                             Found module libxcb-shm.so.0 with build-id: a31877f8ca8058df00055>
                                             Found module libxcb-image.so.0 with build-id: 694d1fef30f01cae164
...


                                           Found module onedrive_tray with build-id: d2018a8fa3cda72487cdddd>
                                             Stack trace of thread 4567:
                                             #0  0x00007f2046d0c56c __pthread_kill_implementation (libc.so.6 +>
                                             #1  0x00007f2046cbfd16 raise (libc.so.6 + 0x54d16)
                                             #2  0x00007f2046c937f3 abort (libc.so.6 + 0x287f3)
                                             #3  0x00007f20472c344b _ZNK14QMessageLogger5fatalEPKcz (libQt5Cor>
                                             #4  0x00007f204790346c _ZN22QGuiApplicationPrivate25createPlatfor>
                                             #5  0x00007f2047903938 _ZN22QGuiApplicationPrivate21createEventDi>
                                             #6  0x00007f20474bf8a3 _ZN23QCoreApplicationPrivate4initEv (libQt>
                                             #7  0x00007f2047905d20 _ZN22QGuiApplicationPrivate4initEv (libQt5>
                                             #8  0x00007f2047f939fd _ZN19QApplicationPrivate4initEv (libQt5Wid>
                                             #9  0x0000000000406026 main (onedrive_tray + 0x6026)
                                             #10 0x00007f2046caaeb0 __libc_start_call_main (libc.so.6 + 0x3feb>
                                             #11 0x00007f2046caaf60 __libc_start_main@@GLIBC_2.34 (libc.so.6 +>
                                             #12 0x00000000004065c5 _start (onedrive_tray + 0x65c5)
Sep 25 14:05:58 z390 dbus-broker-launch[4649]: Ignoring duplicate name 'org.gnome.Extensions' in service file >
Sep 25 14:05:59 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.
Sep 25 14:05:59 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.

Sep 25 14:05:59 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.
Sep 25 14:05:59 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.
Sep 25 14:06:01 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.
Sep 25 14:06:01 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.
Sep 25 14:06:01 z390 systemd[4541]: Failed to start Application launched by gnome-session-binary.
Sep 25 14:06:04 z390 gdm-launch-environment][2497]: GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (obje>
Sep 25 14:06:05 z390 systemd-coredump[6105]: [🡕] Process 6069 (onedrive) of user 1000 dumped core.
                                             
                                             Found module linux-vdso.so.1 with build-id: 4eb75a990aa2bed3769eb>
                                             Found module libnss_resolve.so.2 with build-id: ec863c135a5b61442>
                                             Found module libnss_mdns4_minimal.so.2 with build-id: 6e58847eca4>
                                             Found module libnss_myhostname.so.2 with build-id: 3ec33bb954e08b>
...

                                           Stack trace of thread 6069:
                                             #0  0x0000000000000000 n/a (n/a + 0x0)
Sep 25 14:06:06 z390 abrt-notification[6189]: [🡕] Process 6069 (onedrive) crashed in ??()

but onedrive is working:

![image](https://user-images.githubusercontent.com/20565821/192156787-b60fa7af-ed23-4f87-936c-b167cc4ea037.png)


Onedrive tray is asking me stuffs but I cannot enter "Y" when it try to resync, for exemple. Log is asking me to press Y to continue.

**Comment by DanielBorgesOliveira** [comment]
hi @alansenairj ,

To remove the service just delete the synbolic link **~/.config/systemd/user/default.target.wants/onedrive_tray.service**.

**Comment by alansenairj** [comment]
Thank you!!! Searching for the problem here I think it is related to qt missing something here.
