### ISSUE TITLE
qt6 Painter not active error

### ISSUE THREAD

**Issue by gokomer** [DanielBorgesOliveira/onedrive_tray#40]
Hello,

I've compiled this for qt6 and icons are missing and I get the following errors. Any idea how to fix it?

```
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setCompositionMode: Painter not active
QPainter::end: Painter not active, aborted
```

edit:
I played some more and it looks like these errors caused because QPixmap was empty. If I set QPixmap pixmap(imageName) to QPixmap pixmap(128,128) i get an empty icon and can fill it with solid colors. I couldn't make svg work.

**Comment by DanielBorgesOliveira** [comment]
hi @gokomer 

Could you share the changes you have made?
Maybe this can help anyone migrating the code to QT6.

**Comment by slowsage** [comment]
In case you are using arch: `sudo pacman -S qt5-svg`.

Should be a dependency in PKGBUILD.
