### ISSUE TITLE
Executing a AUR build

### ISSUE THREAD

**Issue by edwardsaunders7** [DanielBorgesOliveira/onedrive_tray#5]
I have just build this from the AUR using YAY; I now however cannot execute the program using your guide. When using `sudo cp systray /usr/local/bin/onedrive_tray` the response I get is `cp: cannot stat 'systray': No such file or directory`

Any advice?

**Comment by jugendhacker** [comment]
The AUR package does the copy stuff for you already... so you don't have to care about anything except starting the tray program with `onedrive_tray`
