### ISSUE TITLE
Segmentation Fault (core dumped) when close configuration window

### ISSUE THREAD

**Issue by maz-1** [DanielBorgesOliveira/onedrive_tray#8]
Happens on archlinux with kde

**Comment by DanielBorgesOliveira** [comment]
Hi @maz-1, can you copy the stacktrace message and post here?

**Comment by bberttsa** [comment]
I have the same issue on Arch + KDE. This is what I found from systemd:

` Process 32718 (onedrive_tray) of user 1000 dumped core.
                                                
                                                Stack trace of thread 32718:
                                                #0  0x00007f315afe8ee0 _ZNK15QSystemTrayIcon9isVisibleEv (libQt5Widgets.so.5 + 0x4d0ee0)
                                                #1  0x0000559698f267ef n/a (onedrive_tray + 0x77ef)
                                                #2  0x00007f315acb2c7e _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x19ac7e)
                                                #3  0x00007f315ac71702 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x159702)
                                                #4  0x00007f315a1a979a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b179a)
                                                #5  0x00007f315acaddf6 _ZN14QWidgetPrivate12close_helperENS_9CloseModeE (libQt5Widgets.so.5 + 0x195df6)
                                                #6  0x00007f315acce8db n/a (libQt5Widgets.so.5 + 0x1b68db)
                                                #7  0x00007f315ac71702 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x159702)
                                                #8  0x00007f315a1a979a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b179a)
                                                #9  0x00007f315a57e00f _ZN22QGuiApplicationPrivate17processCloseEventEPN29QWindowSystemInterfacePrivate10CloseEventE (libQt5Gui.so.5 + 0x13700f)
                                                #10 0x00007f315a556b4c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5 + 0x10fb4c)
                                                #11 0x00007f3156ae4c8c n/a (libQt5XcbQpa.so.5 + 0x5ec8c)
                                                #12 0x00007f315902343c g_main_context_dispatch (libglib-2.0.so.0 + 0x5243c)
                                                #13 0x00007f31590711d9 n/a (libglib-2.0.so.0 + 0xa01d9)
                                                #14 0x00007f3159022221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                #15 0x00007f315a202311 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30a311)
                                                #16 0x00007f315a1a811c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b011c)
                                                #17 0x00007f315a1b05a4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2b85a4)
                                                #18 0x0000559698f24b20 n/a (onedrive_tray + 0x5b20)
                                                #19 0x00007f3159b60152 __libc_start_main (libc.so.6 + 0x28152)
                                                #20 0x0000559698f24c9e n/a (onedrive_tray + 0x5c9e)
                                                
                                                Stack trace of thread 32719:
                                                #0  0x00007f3159c2d46f __poll (libc.so.6 + 0xf546f)
                                                #1  0x00007f3156f5063b n/a (libxcb.so.1 + 0xc63b)
                                                #2  0x00007f3156f5237b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                                                #3  0x00007f3156ae3c51 n/a (libQt5XcbQpa.so.5 + 0x5dc51)
                                                #4  0x00007f3159fc4e0f n/a (libQt5Core.so.5 + 0xcce0f)
                                                #5  0x00007f31599d73e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #6  0x00007f3159c38293 __clone (libc.so.6 + 0x100293)
                                                
                                                Stack trace of thread 32720:
                                                #0  0x00007f3159c2d46f __poll (libc.so.6 + 0xf546f)
                                                #1  0x00007f3159071168 n/a (libglib-2.0.so.0 + 0xa0168)
                                                #2  0x00007f3159022221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                #3  0x00007f315a202311 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30a311)
                                                #4  0x00007f315a1a811c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b011c)
                                                #5  0x00007f3159fc3c32 _ZN7QThread4execEv (libQt5Core.so.5 + 0xcbc32)
                                                #6  0x00007f31569cc098 n/a (libQt5DBus.so.5 + 0x17098)
                                                #7  0x00007f3159fc4e0f n/a (libQt5Core.so.5 + 0xcce0f)
                                                #8  0x00007f31599d73e9 start_thread (libpthread.so.0 + 0x93e9)
                                                #9  0x00007f3159c38293 __clone (libc.so.6 + 0x100293)
                                                
                                                Stack trace of thread 34062:
                                                #0  0x00007f31599dd6a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
`

**Comment by DanielBorgesOliveira** [comment]
Hi @bberttsa ,

Could you try another QT version?
Try to install the version available in [https://www.qt.io/download](https://www.qt.io/download).
I think it is a version problem.
