### ISSUE TITLE
Link to folder

### ISSUE THREAD

**Issue by HTOgit** [DanielBorgesOliveira/onedrive_tray#9]
Can you implement that i.e. double-clicking the icon is a shortcut to the folder?

**Comment by DanielBorgesOliveira** [comment]
Hi @HTOgit ,

I added a Link to Folder feature.
You should click with the right button and select **Open Folder**.
The program will search the folder defined in the onedrive config file and call the xdg-open with that path.

But you should set the variable "sync_dir" in the **~/.config/onedrive/config** folder with the absolute path of the onedrive folder.
E.g.: **sync_dir = "/home/daniel/OneDrive"**

Thank you.

**Comment by HTOgit** [comment]
Hi,

thank you for your effort! But it crashes the program on my systems. Runnig onedrive_tray --onedrive-path with my onedrive-dir it leads to "segmentation fault (core dumped)  onedrive_tray --onedrive-path"
